name: Build and deploy
on:
  push:
    branches:
      - 'master'
      - 'main'
      - 'feature/*'
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
jobs:
  build:
    name: Build Kotlin Application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify -DskipTests
      - run: mkdir staging && cp web/target/*.jar staging
      - run: cp deployment/Dockerfile staging
      - uses: actions/upload-artifact@v3
        with:
          name: Package
          path: staging
