name: check-environments

on:
  push:
    branches:
      - main
      - 'feature/*'

jobs:
  print-vars:
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: Print vars
        env:
          ENV1: ${{ vars.ENV }}
        run: |
          echo "-----------------------"
          echo "$ENV1"
          echo "-----------------------"
          
